# Form implementation generated from reading ui file 'mainapp.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chekDocuments = QtWidgets.QPushButton(self.widget)
        self.chekDocuments.setObjectName("chekDocuments")
        self.verticalLayout_2.addWidget(self.chekDocuments)
        self.OTVSEND = QtWidgets.QPushButton(self.widget)
        self.OTVSEND.setObjectName("OTVSEND")
        self.verticalLayout_2.addWidget(self.OTVSEND)
        self.OTZVSEND = QtWidgets.QPushButton(self.widget)
        self.OTZVSEND.setObjectName("OTZVSEND")
        self.verticalLayout_2.addWidget(self.OTZVSEND)
        self.PESSEND = QtWidgets.QPushButton(self.widget)
        self.PESSEND.setObjectName("PESSEND")
        self.verticalLayout_2.addWidget(self.PESSEND)
        self.RNPSEND = QtWidgets.QPushButton(self.widget)
        self.RNPSEND.setObjectName("RNPSEND")
        self.verticalLayout_2.addWidget(self.RNPSEND)
        self.ZINFSEND = QtWidgets.QPushButton(self.widget)
        self.ZINFSEND.setObjectName("ZINFSEND")
        self.verticalLayout_2.addWidget(self.ZINFSEND)
        self.ZONDSEND = QtWidgets.QPushButton(self.widget)
        self.ZONDSEND.setObjectName("ZONDSEND")
        self.verticalLayout_2.addWidget(self.ZONDSEND)
        self.ZVPSEND = QtWidgets.QPushButton(self.widget)
        self.ZVPSEND.setObjectName("ZVPSEND")
        self.verticalLayout_2.addWidget(self.ZVPSEND)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chekDocuments.setText(_translate("MainWindow", "Проверить документы"))
        self.OTVSEND.setText(_translate("MainWindow", "OTVSEND"))
        self.OTZVSEND.setText(_translate("MainWindow", "OTZVSEND"))
        self.PESSEND.setText(_translate("MainWindow", "PESSEND"))
        self.RNPSEND.setText(_translate("MainWindow", "RNPSEND"))
        self.ZINFSEND.setText(_translate("MainWindow", "ZINFSEND"))
        self.ZONDSEND.setText(_translate("MainWindow", "ZONDSEND"))
        self.ZVPSEND.setText(_translate("MainWindow", "ZVPSEND"))
